### ISSUE TITLE
consistent colours

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#66]
please see attached

![feedback-consistent-colours](https://cloud.githubusercontent.com/assets/7224727/8203330/5055ae36-1524-11e5-9940-40102eb933ab.png)

**Comment by galenp** [comment]
Fixed.

**Comment by anthonyaoun** [comment]
but the old colors are still showing, When will it take affect??

AA

On Thu, Jun 18, 2015 at 2:53 PM, Galen notifications@github.com wrote:

> Fixed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/galenp/PROPERTYCOMPASS.ISSUES/issues/66#issuecomment-113037520
> .

## 

Yours faithfully,

_Anthony Aoun_
Founder

_Confidis Pty Ltd_

_Mobile: *+61 410 510 997
*Office: *+61 3 9028 5001
*Skype:_ anthony.aoun
_Email:_ admin@confidis.com.au
_Web:_ https://confidis.com.au/ http://confidis.com.au/

---

**Comment by galenp** [comment]
the report was changed to match the interface

**Comment by anthonyaoun** [comment]
that is a bit silly given that the 'report page' and 'PDF report' were the
same. Now the 'report page' is INCORRECT

AA

On Thu, Jun 18, 2015 at 3:45 PM, Galen notifications@github.com wrote:

> the report was changed to match the interface
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/galenp/PROPERTYCOMPASS.ISSUES/issues/66#issuecomment-113044542
> .

## 

Yours faithfully,

_Anthony Aoun_
Founder

_Confidis Pty Ltd_

_Mobile: *+61 410 510 997
*Office: *+61 3 9028 5001
*Skype:_ anthony.aoun
_Email:_ admin@confidis.com.au
_Web:_ https://confidis.com.au/ http://confidis.com.au/

---

**Comment by galenp** [comment]
This is the scheme we'll go with.. ill update everything to match.
population - gray
house growth - green
unit growth - blue

**Comment by galenp** [comment]
done
